package services

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"html"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"

	"tunorth-hub-backend/internal/models"
)

// AIQuizGenRequest represents the parameters for generating a quiz via AI
type AIQuizGenRequest struct {
	QuestionCount      int    `json:"question_count"`
	Difficulty         string `json:"difficulty"`          // EASY, MEDIUM, HARD
	QuestionType       string `json:"question_type"`        // MULTIPLE_CHOICE, TRUE_FALSE, MIXED
	CustomInstructions string `json:"custom_instructions"` // Extra guidance
	CustomContext      string `json:"custom_context"`      // Extra text context
	IncludeLessonText  bool   `json:"include_lesson_text"`
	IncludeLessonMedia bool   `json:"include_lesson_media"` // Include PDF / Video attached to lesson
	Model              string `json:"model,omitempty"`

	// Optional direct file upload in modal
	UploadedFileBytes []byte `json:"-"`
	UploadedFileName  string `json:"-"`
	UploadedFileMime  string `json:"-"`
}

// AIQuizQuestionItem represents a single question generated by AI
type AIQuizQuestionItem struct {
	QuestionText  string   `json:"question_text"`
	QuestionType  string   `json:"question_type"` // MULTIPLE_CHOICE, TRUE_FALSE
	Options       []string `json:"options"`
	CorrectAnswer string   `json:"correct_answer"`
	Points        int      `json:"points"`
	Explanation   string   `json:"explanation,omitempty"`
}

// AIQuizGenResult represents the generated quiz structure
type AIQuizGenResult struct {
	QuizTitle   string               `json:"quiz_title"`
	LessonID    string               `json:"lesson_id"`
	LessonTitle string               `json:"lesson_title"`
	Questions   []AIQuizQuestionItem `json:"questions"`
	ModelUsed   string               `json:"model_used"`
	GeneratedAt time.Time            `json:"generated_at"`
}

// MediaPart represents an inline multimodal payload (e.g. PDF or Video)
type MediaPart struct {
	MimeType   string
	Base64Data string
	SourceName string
}

// Interactions API response structures
type interactionStepContent struct {
	Type string `json:"type"`
	Text string `json:"text"`
}

type interactionStep struct {
	Type    string                   `json:"type"`
	Status  string                   `json:"status"`
	Content []interactionStepContent `json:"content"`
}

type interactionResponse struct {
	ID    string            `json:"id"`
	Steps []interactionStep `json:"steps"`
	Error *struct {
		Message string `json:"message"`
		Code    int    `json:"code"`
	} `json:"error,omitempty"`
}

// GetAIGeminiConfig retrieves API key and model from DB with fallback
func GetAIGeminiConfig(db *gorm.DB, envKey string) (apiKey string, model string, enabled bool) {
	enabled = true
	model = "gemini-3.6-flash"

	var settings []models.SystemSetting
	if err := db.Where("category = ? OR key LIKE ?", "AI", "ai_%").Find(&settings).Error; err == nil {
		for _, s := range settings {
			switch s.Key {
			case "ai_gemini_api_key":
				if s.Value != "" {
					apiKey = strings.TrimSpace(s.Value)
				}
			case "ai_default_model":
				if s.Value != "" {
					model = strings.TrimSpace(s.Value)
				}
			case "ai_enabled":
				if strings.ToLower(strings.TrimSpace(s.Value)) == "false" {
					enabled = false
				}
			}
		}
	}

	if apiKey == "" && envKey != "" {
		apiKey = strings.TrimSpace(envKey)
	}

	return apiKey, model, enabled
}

// CleanHTMLToText strips HTML tags and decodes entities into clean readable text
func CleanHTMLToText(htmlStr string) string {
	if htmlStr == "" {
		return ""
	}

	// Remove script and style tags and their contents
	reScript := regexp.MustCompile(`(?is)<script[^>]*>.*?</script>|<style[^>]*>.*?</style>`)
	text := reScript.ReplaceAllString(htmlStr, "")

	// Replace block elements and line breaks with newlines
	reBreak := regexp.MustCompile(`(?i)<(br|p|div|h[1-6]|li|tr)[^>]*>`)
	text = reBreak.ReplaceAllString(text, "\n")

	// Remove all remaining HTML tags
	reTags := regexp.MustCompile(`<[^>]+>`)
	text = reTags.ReplaceAllString(text, " ")

	// Decode HTML entities (e.g. &nbsp;, &amp;, &quot;, &lt;, &gt;)
	text = html.UnescapeString(text)

	// Clean up multiple spaces and empty lines
	lines := strings.Split(text, "\n")
	var cleanedLines []string
	for _, l := range lines {
		trimmed := strings.TrimSpace(l)
		if trimmed != "" {
			cleanedLines = append(cleanedLines, trimmed)
		}
	}

	return strings.Join(cleanedLines, "\n")
}

// GenerateQuizFromLesson builds context, reads multimodal files (PDF/Video), calls Gemini API, and normalizes output
func GenerateQuizFromLesson(ctx context.Context, db *gorm.DB, lessonID uuid.UUID, req AIQuizGenRequest, fallbackEnvKey string) (*AIQuizGenResult, error) {
	apiKey, defaultModel, enabled := GetAIGeminiConfig(db, fallbackEnvKey)
	if !enabled {
		return nil, errors.New("ระบบ AI ช่วยสร้างแบบทดสอบถูกปิดการใช้งานโดยผู้ดูแลระบบ")
	}
	if apiKey == "" {
		return nil, errors.New("ยังไม่ได้ตั้งค่า Google Gemini API Key ในระบบ กรุณาติดต่อผู้ดูแลระบบเพื่อระบุ API Key ที่เมนูตั้งค่าระบบ")
	}

	modelToUse := req.Model
	if modelToUse == "" {
		modelToUse = defaultModel
	}
	if modelToUse == "" {
		modelToUse = "gemini-3.6-flash"
	}

	// Fetch lesson details
	var lesson models.Lesson
	if err := db.First(&lesson, "id = ?", lessonID).Error; err != nil {
		return nil, fmt.Errorf("ไม่พบบทเรียนที่ระบุ: %v", err)
	}

	// Fetch module & course title for rich context
	var module models.Module
	var course models.Course
	courseTitle := ""
	moduleTitle := ""
	if err := db.First(&module, "id = ?", lesson.ModuleID).Error; err == nil {
		moduleTitle = module.Title
		if err := db.First(&course, "id = ?", module.CourseID).Error; err == nil {
			courseTitle = course.Title
		}
	}

	// Determine question parameters
	qCount := req.QuestionCount
	if qCount <= 0 {
		qCount = 5
	}
	if qCount > 20 {
		qCount = 20
	}

	difficulty := strings.ToUpper(strings.TrimSpace(req.Difficulty))
	if difficulty != "EASY" && difficulty != "HARD" {
		difficulty = "MEDIUM"
	}

	qType := strings.ToUpper(strings.TrimSpace(req.QuestionType))
	if qType != "TRUE_FALSE" && qType != "MIXED" {
		qType = "MULTIPLE_CHOICE"
	}

	var mediaParts []MediaPart

	// 1. Process Uploaded File from Modal if present
	if len(req.UploadedFileBytes) > 0 {
		mime := req.UploadedFileMime
		if mime == "" {
			ext := strings.ToLower(filepath.Ext(req.UploadedFileName))
			if ext == ".pdf" {
				mime = "application/pdf"
			} else if ext == ".mp4" {
				mime = "video/mp4"
			}
		}
		if mime == "application/pdf" || strings.HasPrefix(mime, "video/") || strings.HasPrefix(mime, "image/") {
			mediaParts = append(mediaParts, MediaPart{
				MimeType:   mime,
				Base64Data: base64.StdEncoding.EncodeToString(req.UploadedFileBytes),
				SourceName: req.UploadedFileName,
			})
		} else {
			// Plain text file
			req.CustomContext += "\n--- ข้อมูลจากไฟล์เอกสารที่แนบเพิ่มเติม ---\n" + string(req.UploadedFileBytes)
		}
	}

	// 2. Process Lesson's Attached PDF Document if available
	if lesson.PDFURL != "" {
		if media, err := loadLocalMediaFile(lesson.PDFURL, "application/pdf", 25*1024*1024); err == nil {
			mediaParts = append(mediaParts, *media)
		}
	}

	// 3. Process Lesson's Video (YouTube or Local MP4)
	isYouTube := false
	youtubeURL := ""
	if lesson.VideoURL != "" {
		lowerVideo := strings.ToLower(lesson.VideoURL)
		if strings.Contains(lowerVideo, "youtube.com") || strings.Contains(lowerVideo, "youtu.be") {
			isYouTube = true
			youtubeURL = lesson.VideoURL
		} else if strings.HasPrefix(lesson.VideoURL, "/uploads/") || strings.HasPrefix(lesson.VideoURL, "uploads/") {
			// Local video file (up to 25MB for inline multimodal)
			if media, err := loadLocalMediaFile(lesson.VideoURL, "video/mp4", 25*1024*1024); err == nil {
				mediaParts = append(mediaParts, *media)
			}
		}
	}

	// 4. Build Context and Text
	var contentBuilder strings.Builder
	contentBuilder.WriteString(fmt.Sprintf("ชื่อรายวิชา: %s\n", courseTitle))
	contentBuilder.WriteString(fmt.Sprintf("หน่วยการเรียนรู้/โมดูล: %s\n", moduleTitle))
	contentBuilder.WriteString(fmt.Sprintf("ชื่อบทเรียน: %s\n", lesson.Title))
	contentBuilder.WriteString(fmt.Sprintf("รูปแบบบทเรียน: %s\n", lesson.ContentType))

	if isYouTube {
		contentBuilder.WriteString(fmt.Sprintf("\n🎥 ลิงก์คลิปวิดีโอประกอบบทเรียน (YouTube): %s\n", youtubeURL))
		contentBuilder.WriteString("คำแนะนำสำหรับ AI: กรุณาวิเคราะห์เนื้อหา เสียงบรรยาย และสาระสำคัญจากคลิปวิดีโอนี้เพื่อนำมาออกข้อสอบ\n")
	}

	if len(mediaParts) > 0 {
		contentBuilder.WriteString(fmt.Sprintf("\n📄 ไฟล์เอกสาร/สื่อประกอบบทเรียนที่แนบมา: มีไฟล์แนบ %d ไฟล์ (รวมทั้งเอกสาร PDF / วิดีโอ)\n", len(mediaParts)))
		contentBuilder.WriteString("คำแนะนำสำหรับ AI: กรุณาอ่านและวิเคราะห์เนื้อหาจากเอกสาร/ไฟล์แนบ Multimodal เหล่านี้อย่างละเอียดเพื่อสร้างข้อสอบที่ตรงกับเนื้อหาจริง 100%\n")
	}

	if req.IncludeLessonText && lesson.BodyText != "" {
		cleanedText := CleanHTMLToText(lesson.BodyText)
		if cleanedText != "" {
			contentBuilder.WriteString("\n--- เนื้อหาตัวอักษรของบทเรียน (Lesson Content) ---\n")
			contentBuilder.WriteString(cleanedText)
			contentBuilder.WriteString("\n-----------------------------------------------\n")
		}
	}

	if req.CustomContext != "" {
		contentBuilder.WriteString("\n--- เนื้อหาเสริมเพิ่มเติมจากครูผู้สอน ---\n")
		contentBuilder.WriteString(req.CustomContext)
		contentBuilder.WriteString("\n-----------------------------------------\n")
	}

	prompt := buildStrictAIPrompt(contentBuilder.String(), lesson.Title, qCount, difficulty, qType, req.CustomInstructions, len(mediaParts) > 0, isYouTube)

	// Call Gemini API with multimodal attachments
	rawJSON, err := callGeminiMultimodalAPI(ctx, apiKey, modelToUse, prompt, mediaParts)
	if err != nil {
		return nil, err
	}

	// Parse JSON
	var parsedResult struct {
		QuizTitle string               `json:"quiz_title"`
		Questions []AIQuizQuestionItem `json:"questions"`
	}

	cleanJSON := extractJSONBlock(rawJSON)
	if err := json.Unmarshal([]byte(cleanJSON), &parsedResult); err != nil {
		return nil, fmt.Errorf("ไม่สามารถแปลงโครงสร้างข้อสอบจาก AI ได้ (%v): %s", err, cleanJSON)
	}

	// Normalize and validate questions
	normalizedQuestions := make([]AIQuizQuestionItem, 0, len(parsedResult.Questions))
	for _, q := range parsedResult.Questions {
		cleanedQ := normalizeAIQuestion(q)
		if cleanedQ != nil {
			normalizedQuestions = append(normalizedQuestions, *cleanedQ)
		}
	}

	if len(normalizedQuestions) == 0 {
		return nil, errors.New("AI ไม่สามารถสร้างคำถามที่ผ่านเกณฑ์ความถูกต้องได้ กรุณาลองใหม่อีกครั้ง")
	}

	title := strings.TrimSpace(parsedResult.QuizTitle)
	if title == "" {
		title = fmt.Sprintf("แบบทดสอบ: %s", lesson.Title)
	}

	return &AIQuizGenResult{
		QuizTitle:   title,
		LessonID:    lesson.ID.String(),
		LessonTitle: lesson.Title,
		Questions:   normalizedQuestions,
		ModelUsed:   modelToUse,
		GeneratedAt: time.Now(),
	}, nil
}

func loadLocalMediaFile(relOrAbsPath, defaultMime string, maxBytes int64) (*MediaPart, error) {
	cleanPath := strings.TrimPrefix(relOrAbsPath, "/")
	// Check possible relative paths
	candidates := []string{
		cleanPath,
		filepath.Join(".", cleanPath),
		filepath.Join("./uploads", strings.TrimPrefix(cleanPath, "uploads/")),
		filepath.Join("./uploads", cleanPath),
	}

	var foundPath string
	for _, c := range candidates {
		if fi, err := os.Stat(c); err == nil && !fi.IsDir() {
			if maxBytes > 0 && fi.Size() > maxBytes {
				return nil, fmt.Errorf("file size %d exceeds max limit %d", fi.Size(), maxBytes)
			}
			foundPath = c
			break
		}
	}

	if foundPath == "" {
		return nil, fmt.Errorf("local file not found: %s", relOrAbsPath)
	}

	data, err := os.ReadFile(foundPath)
	if err != nil {
		return nil, err
	}

	mime := defaultMime
	ext := strings.ToLower(filepath.Ext(foundPath))
	switch ext {
	case ".pdf":
		mime = "application/pdf"
	case ".mp4":
		mime = "video/mp4"
	case ".webm":
		mime = "video/webm"
	case ".jpg", ".jpeg":
		mime = "image/jpeg"
	case ".png":
		mime = "image/png"
	}

	return &MediaPart{
		MimeType:   mime,
		Base64Data: base64.StdEncoding.EncodeToString(data),
		SourceName: filepath.Base(foundPath),
	}, nil
}

func buildStrictAIPrompt(contextText, lessonTitle string, count int, difficulty, qType, customInstructions string, hasMedia, hasYouTube bool) string {
	var sb strings.Builder

	sb.WriteString("คุณคือผู้เชี่ยวชาญด้านการวัดและประเมินผลทางการศึกษาสำหรับโรงเรียนมัธยมศึกษา (TUNorth-Hub LMS)\n")
	sb.WriteString(fmt.Sprintf("เป้าหมาย: สร้างชุดแบบทดสอบวัดความรู้ท้ายบทเรียนเรื่อง \"%s\" จำนวน %d ข้อ\n\n", lessonTitle, count))

	sb.WriteString("กฎเหล็กสำหรับการสร้างข้อสอบ (STRICT CONTENT GROUNDING RULES):\n")
	sb.WriteString("1. **ความถูกต้องตรงตามเนื้อหา (Strict Grounding)**: ข้อสอบทุกข้อต้องอ้างอิงและวัดความรู้จากเนื้อหาที่ส่งให้เท่านั้น (ทั้งจากเอกสาร PDF, คลิปวิดีโอ, หรือเนื้อหาบทเรียน)\n")
	sb.WriteString("2. **ห้ามคาดเดาจากแค่ชื่อเรื่อง**: ห้ามสร้างคำถามทั่วไปที่ไม่ปรากฏในเนื้อหาเอกสารหรือคลิป\n")
	sb.WriteString(fmt.Sprintf("3. **ระดับความยาก**: %s (EASY = วัดความจำ/นิยามตามเอกสาร, MEDIUM = วัดความเข้าใจ/การประยุกต์, HARD = วัดการวิเคราะห์/แก้โจทย์ปัญหา)\n", difficulty))

	switch qType {
	case "TRUE_FALSE":
		sb.WriteString("4. **ชนิดข้อสอบ**: ข้อสอบแบบ ถูก/ผิด (TRUE_FALSE) ทุกข้อ โดยตัวเลือกต้องเป็น [\"จริง\", \"เท็จ\"]\n")
	case "MIXED":
		sb.WriteString("4. **ชนิดข้อสอบ**: ผสมผสานระหว่าง ปรนัย 4 ตัวเลือก (MULTIPLE_CHOICE) และ ถูก/ผิด (TRUE_FALSE)\n")
	default:
		sb.WriteString("4. **ชนิดข้อสอบ**: ปรนัย 4 ตัวเลือก (MULTIPLE_CHOICE) ที่มีตัวเลือก ก, ข, ค, ง สมเหตุสมผลและสอดคล้องกับเนื้อหา\n")
	}

	sb.WriteString("5. **เฉลย (correct_answer)**: ต้องระบุข้อความตรงกับ 1 ในตัวเลือกที่กำหนดไว้อย่างแม่นยำ 100%\n")
	sb.WriteString("6. **คำอธิบายเฉลย (explanation)**: สรุปเหตุผลสั้นๆ พร้อมระบุตำแหน่ง/หัวข้อหรือช่วงเวลาในเนื้อหาที่ใช้อ้างอิง\n")
	sb.WriteString("7. **ภาษา**: ภาษาไทยที่ถูกต้อง ชัดเจน ตรงตามหลักวิชาการ\n")

	if customInstructions != "" {
		sb.WriteString(fmt.Sprintf("8. **คำสั่งพิเศษเพิ่มเติมจากครูผู้สอน**: %s\n", customInstructions))
	}

	sb.WriteString("\n--- ข้อมูลบริบทและเนื้อหาบทเรียน ---\n")
	sb.WriteString(contextText)
	sb.WriteString("\n------------------------------------\n")

	sb.WriteString("\nรูปแบบผลลัพธ์: ตอบกลับเป็น JSON ในรูปแบบนี้เท่านั้น (ห้ามใส่คำเกริ่นนำหรือ Markdown code fence อื่นนอกเหนือจาก JSON):\n")
	sb.WriteString(`{
  "quiz_title": "แบบทดสอบท้ายบทเรียน: ...",
  "questions": [
    {
      "question_text": "โจทย์คำถาม...",
      "question_type": "MULTIPLE_CHOICE",
      "options": ["ตัวเลือก 1", "ตัวเลือก 2", "ตัวเลือก 3", "ตัวเลือก 4"],
      "correct_answer": "ตัวเลือก 1",
      "points": 1,
      "explanation": "เหตุผลที่ตัวเลือกนี้ถูกต้อง..."
    }
  ]
}`)

	return sb.String()
}

func callGeminiMultimodalAPI(ctx context.Context, apiKey, model, prompt string, mediaParts []MediaPart) (string, error) {
	client := &http.Client{
		Timeout: 75 * time.Second,
	}

	// 1. Build parts: inline media parts first, then prompt text part
	var parts []map[string]interface{}
	for _, m := range mediaParts {
		parts = append(parts, map[string]interface{}{
			"inlineData": map[string]interface{}{
				"mimeType": m.MimeType,
				"data":     m.Base64Data,
			},
		})
	}
	parts = append(parts, map[string]interface{}{
		"text": prompt,
	})

	genContentURL := fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s", model, apiKey)
	genPayload := map[string]interface{}{
		"contents": []map[string]interface{}{
			{
				"parts": parts,
			},
		},
		"generationConfig": map[string]interface{}{
			"responseMimeType": "application/json",
			"temperature":      0.2,
		},
	}

	jsonBytes, err := json.Marshal(genPayload)
	if err == nil {
		httpReq, reqErr := http.NewRequestWithContext(ctx, "POST", genContentURL, bytes.NewBuffer(jsonBytes))
		if reqErr == nil {
			httpReq.Header.Set("Content-Type", "application/json")
			httpReq.Header.Set("x-goog-api-key", apiKey)

			resp, doErr := client.Do(httpReq)
			if doErr == nil {
				defer resp.Body.Close()
				respBody, _ := io.ReadAll(resp.Body)

				if resp.StatusCode == http.StatusOK {
					// Parse standard generateContent response
					var genResp struct {
						Candidates []struct {
							Content struct {
								Parts []struct {
									Text string `json:"text"`
								} `json:"parts"`
							} `json:"content"`
						} `json:"candidates"`
					}
					if err := json.Unmarshal(respBody, &genResp); err == nil && len(genResp.Candidates) > 0 {
						var sb strings.Builder
						for _, part := range genResp.Candidates[0].Content.Parts {
							sb.WriteString(part.Text)
						}
						if sb.Len() > 0 {
							return sb.String(), nil
						}
					}
					return string(respBody), nil
				}
			}
		}
	}

	// 2. Fallback to Interactions API if needed
	interactionsURL := fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta2/interactions?key=%s", apiKey)
	interPayload := map[string]interface{}{
		"model": model,
		"input": prompt,
		"response_format": []map[string]interface{}{
			{
				"type":      "text",
				"mime_type": "application/json",
			},
		},
	}

	interBytes, err := json.Marshal(interPayload)
	if err != nil {
		return "", fmt.Errorf("error marshalling payload: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", interactionsURL, bytes.NewBuffer(interBytes))
	if err != nil {
		return "", fmt.Errorf("error creating request: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("x-goog-api-key", apiKey)

	resp, err := client.Do(httpReq)
	if err != nil {
		return "", fmt.Errorf("ไม่สามารถติดต่อ Google Gemini API ได้: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("error reading response: %w", err)
	}

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		var errData map[string]interface{}
		_ = json.Unmarshal(respBody, &errData)
		errMsg := fmt.Sprintf("Google API error (status %d)", resp.StatusCode)
		if e, ok := errData["error"].(map[string]interface{}); ok {
			if msg, ok := e["message"].(string); ok {
				errMsg = msg
			}
		}
		return "", fmt.Errorf("Google Gemini API: %s", errMsg)
	}

	// Parse Interactions API response
	var interResp interactionResponse
	if err := json.Unmarshal(respBody, &interResp); err == nil && len(interResp.Steps) > 0 {
		var sb strings.Builder
		for _, step := range interResp.Steps {
			if step.Type == "model_output" || step.Type == "output" || step.Type == "" {
				for _, c := range step.Content {
					if c.Text != "" {
						sb.WriteString(c.Text)
					}
				}
			}
		}
		if sb.Len() > 0 {
			return sb.String(), nil
		}
	}

	return string(respBody), nil
}

func extractJSONBlock(raw string) string {
	raw = strings.TrimSpace(raw)
	if strings.HasPrefix(raw, "```json") {
		raw = strings.TrimPrefix(raw, "```json")
		if idx := strings.LastIndex(raw, "```"); idx != -1 {
			raw = raw[:idx]
		}
	} else if strings.HasPrefix(raw, "```") {
		raw = strings.TrimPrefix(raw, "```")
		if idx := strings.LastIndex(raw, "```"); idx != -1 {
			raw = raw[:idx]
		}
	}
	return strings.TrimSpace(raw)
}

func normalizeAIQuestion(q AIQuizQuestionItem) *AIQuizQuestionItem {
	qText := strings.TrimSpace(q.QuestionText)
	if qText == "" {
		return nil
	}

	qType := strings.ToUpper(strings.TrimSpace(q.QuestionType))
	if qType == "TRUE_FALSE" || qType == "TF" {
		qType = "TRUE_FALSE"
		options := []string{"จริง", "เท็จ"}
		corr := strings.TrimSpace(q.CorrectAnswer)
		corrLower := strings.ToLower(corr)

		if corrLower == "true" || corrLower == "t" || corr == "จริง" || corr == "ถูก" || corr == "1" || corr == "ก" {
			corr = "จริง"
		} else {
			corr = "เท็จ"
		}

		pts := q.Points
		if pts <= 0 {
			pts = 1
		}

		return &AIQuizQuestionItem{
			QuestionText:  qText,
			QuestionType:  "TRUE_FALSE",
			Options:       options,
			CorrectAnswer: corr,
			Points:        pts,
			Explanation:   strings.TrimSpace(q.Explanation),
		}
	}

	// MULTIPLE_CHOICE
	cleanedOptions := make([]string, 0, len(q.Options))
	for _, opt := range q.Options {
		trimmed := strings.TrimSpace(opt)
		if trimmed != "" {
			cleanedOptions = append(cleanedOptions, trimmed)
		}
	}

	if len(cleanedOptions) < 2 {
		return nil
	}

	corr := strings.TrimSpace(q.CorrectAnswer)
	// Check if correct answer matches any option
	matched := false
	for _, opt := range cleanedOptions {
		if strings.EqualFold(opt, corr) {
			corr = opt
			matched = true
			break
		}
	}

	// If not directly matched, check if it's an index like A, B, C, D or 1, 2, 3, 4 or ก, ข, ค, ง
	if !matched {
		corrLower := strings.ToLower(corr)
		idx := -1
		switch corrLower {
		case "a", "1", "ก":
			idx = 0
		case "b", "2", "ข":
			idx = 1
		case "c", "3", "ค":
			idx = 2
		case "d", "4", "ง":
			idx = 3
		}
		if idx >= 0 && idx < len(cleanedOptions) {
			corr = cleanedOptions[idx]
			matched = true
		}
	}

	if !matched {
		// Default to first option if no match found
		corr = cleanedOptions[0]
	}

	pts := q.Points
	if pts <= 0 {
		pts = 1
	}

	return &AIQuizQuestionItem{
		QuestionText:  qText,
		QuestionType:  "MULTIPLE_CHOICE",
		Options:       cleanedOptions,
		CorrectAnswer: corr,
		Points:        pts,
		Explanation:   strings.TrimSpace(q.Explanation),
	}
}
