package services

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"html"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"

	"tunorth-hub-backend/internal/models"
)

// AIQuizGenRequest represents the parameters for generating a quiz via AI
type AIQuizGenRequest struct {
	QuestionCount      int    `json:"question_count"`
	Difficulty         string `json:"difficulty"`          // EASY, MEDIUM, HARD
	QuestionType       string `json:"question_type"`        // MULTIPLE_CHOICE, TRUE_FALSE, MIXED
	CustomInstructions string `json:"custom_instructions"` // Extra guidance
	CustomContext      string `json:"custom_context"`      // Extra text context
	IncludeLessonText  bool   `json:"include_lesson_text"`
	IncludeLessonMedia bool   `json:"include_lesson_media"` // Include PDF / Video attached to lesson
	Provider           string `json:"provider,omitempty"`   // gemini, openai, anthropic, custom
	Model              string `json:"model,omitempty"`

	// Optional direct file upload in modal
	UploadedFileBytes []byte `json:"-"`
	UploadedFileName  string `json:"-"`
	UploadedFileMime  string `json:"-"`
}

// AIQuizQuestionItem represents a single question generated by AI
type AIQuizQuestionItem struct {
	QuestionText  string   `json:"question_text"`
	QuestionType  string   `json:"question_type"` // MULTIPLE_CHOICE, TRUE_FALSE
	Options       []string `json:"options"`
	CorrectAnswer string   `json:"correct_answer"`
	Points        int      `json:"points"`
	Explanation   string   `json:"explanation,omitempty"`
}

// AIQuizGenResult represents the generated quiz structure
type AIQuizGenResult struct {
	QuizTitle    string               `json:"quiz_title"`
	LessonID     string               `json:"lesson_id"`
	LessonTitle  string               `json:"lesson_title"`
	Questions    []AIQuizQuestionItem `json:"questions"`
	ProviderUsed string               `json:"provider_used"`
	ModelUsed    string               `json:"model_used"`
	GeneratedAt  time.Time            `json:"generated_at"`
}

// MediaPart represents an inline multimodal payload (e.g. PDF or Video)
type MediaPart struct {
	MimeType   string
	Base64Data string
	SourceName string
}

// AIProviderConfig contains the full resolved AI configuration
type AIProviderConfig struct {
	Enabled  bool
	Provider string // gemini, openai, anthropic, custom
	APIKey   string
	Model    string
	BaseURL  string
}

// GetAIConfig retrieves active AI provider configuration from DB with fallbacks
func GetAIConfig(db *gorm.DB, envKey string) AIProviderConfig {
	cfg := AIProviderConfig{
		Enabled:  true,
		Provider: "gemini",
		Model:    "gemini-3.6-flash",
		BaseURL:  "https://api.deepseek.com/v1",
	}

	var settings []models.SystemSetting
	settingsMap := make(map[string]string)
	if err := db.Where("category = ? OR key LIKE ?", "AI", "ai_%").Find(&settings).Error; err == nil {
		for _, s := range settings {
			settingsMap[s.Key] = strings.TrimSpace(s.Value)
		}
	}

	if val, ok := settingsMap["ai_enabled"]; ok {
		if strings.ToLower(val) == "false" {
			cfg.Enabled = false
		}
	}

	if val, ok := settingsMap["ai_provider"]; ok && val != "" {
		cfg.Provider = strings.ToLower(val)
	}

	// Resolve provider-specific keys and models
	switch cfg.Provider {
	case "openai":
		cfg.APIKey = settingsMap["ai_openai_api_key"]
		cfg.Model = settingsMap["ai_openai_model"]
		if cfg.Model == "" {
			cfg.Model = "gpt-4o-mini"
		}
		cfg.BaseURL = "https://api.openai.com/v1"

	case "anthropic":
		cfg.APIKey = settingsMap["ai_anthropic_api_key"]
		cfg.Model = settingsMap["ai_anthropic_model"]
		if cfg.Model == "" {
			cfg.Model = "claude-3-5-haiku-latest"
		}
		cfg.BaseURL = "https://api.anthropic.com/v1"

	case "custom":
		cfg.APIKey = settingsMap["ai_custom_api_key"]
		cfg.Model = settingsMap["ai_custom_model"]
		if cfg.Model == "" {
			cfg.Model = "deepseek-chat"
		}
		cfg.BaseURL = settingsMap["ai_custom_base_url"]
		if cfg.BaseURL == "" {
			cfg.BaseURL = "https://api.deepseek.com/v1"
		}

	default: // gemini
		cfg.Provider = "gemini"
		cfg.APIKey = settingsMap["ai_gemini_api_key"]
		if cfg.APIKey == "" && envKey != "" {
			cfg.APIKey = strings.TrimSpace(envKey)
		}
		cfg.Model = settingsMap["ai_gemini_model"]
		if cfg.Model == "" {
			cfg.Model = settingsMap["ai_default_model"]
		}
		if cfg.Model == "" {
			cfg.Model = "gemini-3.6-flash"
		}
	}

	return cfg
}

// GetAIGeminiConfig preserves backward compatibility
func GetAIGeminiConfig(db *gorm.DB, envKey string) (apiKey string, model string, enabled bool) {
	cfg := GetAIConfig(db, envKey)
	return cfg.APIKey, cfg.Model, cfg.Enabled
}

// CleanHTMLToText strips HTML tags and decodes entities into clean readable text
func CleanHTMLToText(htmlStr string) string {
	if htmlStr == "" {
		return ""
	}

	// Remove script and style tags and their contents
	reScript := regexp.MustCompile(`(?is)<script[^>]*>.*?</script>|<style[^>]*>.*?</style>`)
	text := reScript.ReplaceAllString(htmlStr, "")

	// Replace block elements and line breaks with newlines
	reBreak := regexp.MustCompile(`(?i)<(br|p|div|h[1-6]|li|tr)[^>]*>`)
	text = reBreak.ReplaceAllString(text, "\n")

	// Remove all remaining HTML tags
	reTags := regexp.MustCompile(`<[^>]+>`)
	text = reTags.ReplaceAllString(text, " ")

	// Decode HTML entities
	text = html.UnescapeString(text)

	// Clean up multiple spaces and empty lines
	lines := strings.Split(text, "\n")
	var cleanedLines []string
	for _, l := range lines {
		trimmed := strings.TrimSpace(l)
		if trimmed != "" {
			cleanedLines = append(cleanedLines, trimmed)
		}
	}

	return strings.Join(cleanedLines, "\n")
}

// GenerateQuizFromLesson builds context, reads multimodal files (PDF/Video), calls selected AI Provider, and normalizes output
func GenerateQuizFromLesson(ctx context.Context, db *gorm.DB, lessonID uuid.UUID, req AIQuizGenRequest, fallbackEnvKey string) (*AIQuizGenResult, error) {
	cfg := GetAIConfig(db, fallbackEnvKey)
	if !cfg.Enabled {
		return nil, errors.New("ระบบ AI ช่วยสร้างแบบทดสอบถูกปิดการใช้งานโดยผู้ดูแลระบบ")
	}

	// Allow request to override provider or model if specified
	if req.Provider != "" {
		cfg.Provider = strings.ToLower(req.Provider)
	}
	if req.Model != "" {
		cfg.Model = req.Model
	}

	if cfg.APIKey == "" && cfg.Provider != "custom" {
		return nil, fmt.Errorf("ยังไม่ได้ตั้งค่า API Key สำหรับผู้ให้บริการ %s กรุณาระบุ API Key ที่เมนูตั้งค่าระบบ (Admin Settings)", strings.ToUpper(cfg.Provider))
	}

	// Fetch lesson details
	var lesson models.Lesson
	if err := db.First(&lesson, "id = ?", lessonID).Error; err != nil {
		return nil, fmt.Errorf("ไม่พบบทเรียนที่ระบุ: %v", err)
	}

	// Fetch module & course title for rich context
	var module models.Module
	var course models.Course
	courseTitle := ""
	moduleTitle := ""
	if err := db.First(&module, "id = ?", lesson.ModuleID).Error; err == nil {
		moduleTitle = module.Title
		if err := db.First(&course, "id = ?", module.CourseID).Error; err == nil {
			courseTitle = course.Title
		}
	}

	// Determine question parameters
	qCount := req.QuestionCount
	if qCount <= 0 {
		qCount = 5
	}
	if qCount > 20 {
		qCount = 20
	}

	difficulty := strings.ToUpper(strings.TrimSpace(req.Difficulty))
	if difficulty != "EASY" && difficulty != "HARD" {
		difficulty = "MEDIUM"
	}

	qType := strings.ToUpper(strings.TrimSpace(req.QuestionType))
	if qType != "TRUE_FALSE" && qType != "MIXED" {
		qType = "MULTIPLE_CHOICE"
	}

	var mediaParts []MediaPart

	// 1. Process Uploaded File from Modal if present
	if len(req.UploadedFileBytes) > 0 {
		mime := req.UploadedFileMime
		if mime == "" {
			ext := strings.ToLower(filepath.Ext(req.UploadedFileName))
			if ext == ".pdf" {
				mime = "application/pdf"
			} else if ext == ".mp4" {
				mime = "video/mp4"
			}
		}
		if mime == "application/pdf" || strings.HasPrefix(mime, "video/") || strings.HasPrefix(mime, "image/") {
			mediaParts = append(mediaParts, MediaPart{
				MimeType:   mime,
				Base64Data: base64.StdEncoding.EncodeToString(req.UploadedFileBytes),
				SourceName: req.UploadedFileName,
			})
		} else {
			// Plain text file
			req.CustomContext += "\n--- ข้อมูลจากไฟล์เอกสารที่แนบเพิ่มเติม ---\n" + string(req.UploadedFileBytes)
		}
	}

	// 2. Process Lesson's Attached PDF Document if available
	if lesson.PDFURL != "" {
		if media, err := loadLocalMediaFile(lesson.PDFURL, "application/pdf", 25*1024*1024); err == nil {
			mediaParts = append(mediaParts, *media)
		}
	}

	// 3. Process Lesson's Video (YouTube or Local MP4)
	isYouTube := false
	youtubeURL := ""
	if lesson.VideoURL != "" {
		lowerVideo := strings.ToLower(lesson.VideoURL)
		if strings.Contains(lowerVideo, "youtube.com") || strings.Contains(lowerVideo, "youtu.be") {
			isYouTube = true
			youtubeURL = lesson.VideoURL
		} else if strings.HasPrefix(lesson.VideoURL, "/uploads/") || strings.HasPrefix(lesson.VideoURL, "uploads/") {
			// Local video file (up to 25MB for inline multimodal)
			if media, err := loadLocalMediaFile(lesson.VideoURL, "video/mp4", 25*1024*1024); err == nil {
				mediaParts = append(mediaParts, *media)
			}
		}
	}

	// 4. Build Context and Text
	var contentBuilder strings.Builder
	contentBuilder.WriteString(fmt.Sprintf("ชื่อรายวิชา: %s\n", courseTitle))
	contentBuilder.WriteString(fmt.Sprintf("หน่วยการเรียนรู้/โมดูล: %s\n", moduleTitle))
	contentBuilder.WriteString(fmt.Sprintf("ชื่อบทเรียน: %s\n", lesson.Title))
	contentBuilder.WriteString(fmt.Sprintf("รูปแบบบทเรียน: %s\n", lesson.ContentType))

	if isYouTube {
		contentBuilder.WriteString(fmt.Sprintf("\n🎥 ลิงก์คลิปวิดีโอประกอบบทเรียน (YouTube): %s\n", youtubeURL))
		contentBuilder.WriteString("คำแนะนำสำหรับ AI: กรุณาวิเคราะห์เนื้อหา เสียงบรรยาย และสาระสำคัญจากคลิปวิดีโอนี้เพื่อนำมาออกข้อสอบ\n")
	}

	if len(mediaParts) > 0 {
		contentBuilder.WriteString(fmt.Sprintf("\n📄 ไฟล์เอกสาร/สื่อประกอบบทเรียนที่แนบมา: มีไฟล์แนบ %d ไฟล์ (รวมทั้งเอกสาร PDF / วิดีโอ)\n", len(mediaParts)))
		contentBuilder.WriteString("คำแนะนำสำหรับ AI: กรุณาอ่านและวิเคราะห์เนื้อหาจากเอกสาร/ไฟล์แนบ Multimodal เหล่านี้อย่างละเอียดเพื่อสร้างข้อสอบที่ตรงกับเนื้อหาจริง 100%\n")
	}

	if req.IncludeLessonText && lesson.BodyText != "" {
		cleanedText := CleanHTMLToText(lesson.BodyText)
		if cleanedText != "" {
			contentBuilder.WriteString("\n--- เนื้อหาตัวอักษรของบทเรียน (Lesson Content) ---\n")
			contentBuilder.WriteString(cleanedText)
			contentBuilder.WriteString("\n-----------------------------------------------\n")
		}
	}

	if req.CustomContext != "" {
		contentBuilder.WriteString("\n--- เนื้อหาเสริมเพิ่มเติมจากครูผู้สอน ---\n")
		contentBuilder.WriteString(req.CustomContext)
		contentBuilder.WriteString("\n-----------------------------------------\n")
	}

	prompt := buildStrictAIPrompt(contentBuilder.String(), lesson.Title, qCount, difficulty, qType, req.CustomInstructions, len(mediaParts) > 0, isYouTube)

	// Call specific AI Provider
	var rawJSON string
	var err error

	switch cfg.Provider {
	case "openai":
		rawJSON, err = callOpenAIChatAPI(ctx, cfg.APIKey, cfg.BaseURL, cfg.Model, prompt)
	case "anthropic":
		rawJSON, err = callAnthropicMessagesAPI(ctx, cfg.APIKey, cfg.Model, prompt, mediaParts)
	case "custom":
		rawJSON, err = callOpenAICompatibleAPI(ctx, cfg.APIKey, cfg.BaseURL, cfg.Model, prompt)
	default: // gemini
		rawJSON, err = callGeminiMultimodalAPI(ctx, cfg.APIKey, cfg.Model, prompt, mediaParts)
	}

	if err != nil {
		return nil, fmt.Errorf("[%s] %w", strings.ToUpper(cfg.Provider), err)
	}

	// Parse JSON
	var parsedResult struct {
		QuizTitle string               `json:"quiz_title"`
		Questions []AIQuizQuestionItem `json:"questions"`
	}

	cleanJSON := extractJSONBlock(rawJSON)
	if err := json.Unmarshal([]byte(cleanJSON), &parsedResult); err != nil {
		return nil, fmt.Errorf("ไม่สามารถแปลงโครงสร้างข้อสอบจาก AI ได้ (%v): %s", err, cleanJSON)
	}

	// Normalize and validate questions
	normalizedQuestions := make([]AIQuizQuestionItem, 0, len(parsedResult.Questions))
	for _, q := range parsedResult.Questions {
		cleanedQ := normalizeAIQuestion(q)
		if cleanedQ != nil {
			normalizedQuestions = append(normalizedQuestions, *cleanedQ)
		}
	}

	if len(normalizedQuestions) == 0 {
		return nil, errors.New("AI ไม่สามารถสร้างคำถามที่ผ่านเกณฑ์ความถูกต้องได้ กรุณาลองใหม่อีกครั้ง")
	}

	title := strings.TrimSpace(parsedResult.QuizTitle)
	if title == "" {
		title = fmt.Sprintf("แบบทดสอบ: %s", lesson.Title)
	}

	return &AIQuizGenResult{
		QuizTitle:    title,
		LessonID:     lesson.ID.String(),
		LessonTitle:  lesson.Title,
		Questions:    normalizedQuestions,
		ProviderUsed: cfg.Provider,
		ModelUsed:    cfg.Model,
		GeneratedAt:  time.Now(),
	}, nil
}

func loadLocalMediaFile(relOrAbsPath, defaultMime string, maxBytes int64) (*MediaPart, error) {
	cleanPath := strings.TrimPrefix(relOrAbsPath, "/")
	candidates := []string{
		cleanPath,
		filepath.Join(".", cleanPath),
		filepath.Join("./uploads", strings.TrimPrefix(cleanPath, "uploads/")),
		filepath.Join("./uploads", cleanPath),
	}

	var foundPath string
	for _, c := range candidates {
		if fi, err := os.Stat(c); err == nil && !fi.IsDir() {
			if maxBytes > 0 && fi.Size() > maxBytes {
				return nil, fmt.Errorf("file size %d exceeds max limit %d", fi.Size(), maxBytes)
			}
			foundPath = c
			break
		}
	}

	if foundPath == "" {
		return nil, fmt.Errorf("local file not found: %s", relOrAbsPath)
	}

	data, err := os.ReadFile(foundPath)
	if err != nil {
		return nil, err
	}

	mime := defaultMime
	ext := strings.ToLower(filepath.Ext(foundPath))
	switch ext {
	case ".pdf":
		mime = "application/pdf"
	case ".mp4":
		mime = "video/mp4"
	case ".webm":
		mime = "video/webm"
	case ".jpg", ".jpeg":
		mime = "image/jpeg"
	case ".png":
		mime = "image/png"
	}

	return &MediaPart{
		MimeType:   mime,
		Base64Data: base64.StdEncoding.EncodeToString(data),
		SourceName: filepath.Base(foundPath),
	}, nil
}

func buildStrictAIPrompt(contextText, lessonTitle string, count int, difficulty, qType, customInstructions string, hasMedia, hasYouTube bool) string {
	var sb strings.Builder

	sb.WriteString("คุณคือผู้เชี่ยวชาญด้านการวัดและประเมินผลทางการศึกษาสำหรับโรงเรียนมัธยมศึกษา (TUNorth-Hub LMS)\n")
	sb.WriteString(fmt.Sprintf("เป้าหมาย: สร้างชุดแบบทดสอบวัดความรู้ท้ายบทเรียนเรื่อง \"%s\" จำนวน %d ข้อ\n\n", lessonTitle, count))

	sb.WriteString("กฎเหล็กสำหรับการสร้างข้อสอบ (STRICT CONTENT GROUNDING RULES):\n")
	sb.WriteString("1. **ความถูกต้องตรงตามเนื้อหา (Strict Grounding)**: ข้อสอบทุกข้อต้องอ้างอิงและวัดความรู้จากเนื้อหาที่ส่งให้เท่านั้น (ทั้งจากเอกสาร PDF, คลิปวิดีโอ, หรือเนื้อหาบทเรียน)\n")
	sb.WriteString("2. **ห้ามคาดเดาจากแค่ชื่อเรื่อง**: ห้ามสร้างคำถามทั่วไปที่ไม่ปรากฏในเนื้อหาเอกสารหรือคลิป\n")
	sb.WriteString(fmt.Sprintf("3. **ระดับความยาก**: %s (EASY = วัดความจำ/นิยามตามเอกสาร, MEDIUM = วัดความเข้าใจ/การประยุกต์, HARD = วัดการวิเคราะห์/แก้โจทย์ปัญหา)\n", difficulty))

	switch qType {
	case "TRUE_FALSE":
		sb.WriteString("4. **ชนิดข้อสอบ**: ข้อสอบแบบ ถูก/ผิด (TRUE_FALSE) ทุกข้อ โดยตัวเลือกต้องเป็น [\"จริง\", \"เท็จ\"]\n")
	case "MIXED":
		sb.WriteString("4. **ชนิดข้อสอบ**: ผสมผสานระหว่าง ปรนัย 4 ตัวเลือก (MULTIPLE_CHOICE) และ ถูก/ผิด (TRUE_FALSE)\n")
	default:
		sb.WriteString("4. **ชนิดข้อสอบ**: ปรนัย 4 ตัวเลือก (MULTIPLE_CHOICE) ที่มีตัวเลือก ก, ข, ค, ง สมเหตุสมผลและสอดคล้องกับเนื้อหา\n")
	}

	sb.WriteString("5. **เฉลย (correct_answer)**: ต้องระบุข้อความตรงกับ 1 ในตัวเลือกที่กำหนดไว้อย่างแม่นยำ 100%\n")
	sb.WriteString("6. **คำอธิบายเฉลย (explanation)**: สรุปเหตุผลสั้นๆ พร้อมระบุตำแหน่ง/หัวข้อหรือช่วงเวลาในเนื้อหาที่ใช้อ้างอิง\n")
	sb.WriteString("7. **ภาษา**: ภาษาไทยที่ถูกต้อง ชัดเจน ตรงตามหลักวิชาการ\n")

	if customInstructions != "" {
		sb.WriteString(fmt.Sprintf("8. **คำสั่งพิเศษเพิ่มเติมจากครูผู้สอน**: %s\n", customInstructions))
	}

	sb.WriteString("\n--- ข้อมูลบริบทและเนื้อหาบทเรียน ---\n")
	sb.WriteString(contextText)
	sb.WriteString("\n------------------------------------\n")

	sb.WriteString("\nรูปแบบผลลัพธ์: ตอบกลับเป็น JSON ในรูปแบบนี้เท่านั้น (ห้ามใส่คำเกริ่นนำหรือ Markdown code fence อื่นนอกเหนือจาก JSON):\n")
	sb.WriteString(`{
  "quiz_title": "แบบทดสอบท้ายบทเรียน: ...",
  "questions": [
    {
      "question_text": "โจทย์คำถาม...",
      "question_type": "MULTIPLE_CHOICE",
      "options": ["ตัวเลือก 1", "ตัวเลือก 2", "ตัวเลือก 3", "ตัวเลือก 4"],
      "correct_answer": "ตัวเลือก 1",
      "points": 1,
      "explanation": "เหตุผลที่ตัวเลือกนี้ถูกต้อง..."
    }
  ]
}`)

	return sb.String()
}

// -------------------------------------------------------------
// PROVIDER 1: Google Gemini API
// -------------------------------------------------------------
func callGeminiMultimodalAPI(ctx context.Context, apiKey, model, prompt string, mediaParts []MediaPart) (string, error) {
	client := &http.Client{
		Timeout: 75 * time.Second,
	}

	var parts []map[string]interface{}
	for _, m := range mediaParts {
		parts = append(parts, map[string]interface{}{
			"inlineData": map[string]interface{}{
				"mimeType": m.MimeType,
				"data":     m.Base64Data,
			},
		})
	}
	parts = append(parts, map[string]interface{}{
		"text": prompt,
	})

	genContentURL := fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s", model, apiKey)
	genPayload := map[string]interface{}{
		"contents": []map[string]interface{}{
			{
				"parts": parts,
			},
		},
		"generationConfig": map[string]interface{}{
			"responseMimeType": "application/json",
			"temperature":      0.2,
		},
	}

	jsonBytes, err := json.Marshal(genPayload)
	if err == nil {
		httpReq, reqErr := http.NewRequestWithContext(ctx, "POST", genContentURL, bytes.NewBuffer(jsonBytes))
		if reqErr == nil {
			httpReq.Header.Set("Content-Type", "application/json")
			httpReq.Header.Set("x-goog-api-key", apiKey)

			resp, doErr := client.Do(httpReq)
			if doErr == nil {
				defer resp.Body.Close()
				respBody, _ := io.ReadAll(resp.Body)

				if resp.StatusCode == http.StatusOK {
					var genResp struct {
						Candidates []struct {
							Content struct {
								Parts []struct {
									Text string `json:"text"`
								} `json:"parts"`
							} `json:"content"`
						} `json:"candidates"`
					}
					if err := json.Unmarshal(respBody, &genResp); err == nil && len(genResp.Candidates) > 0 {
						var sb strings.Builder
						for _, part := range genResp.Candidates[0].Content.Parts {
							sb.WriteString(part.Text)
						}
						if sb.Len() > 0 {
							return sb.String(), nil
						}
					}
					return string(respBody), nil
				}
			}
		}
	}

	// Fallback to Interactions API
	interactionsURL := fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta2/interactions?key=%s", apiKey)
	interPayload := map[string]interface{}{
		"model": model,
		"input": prompt,
		"response_format": []map[string]interface{}{
			{
				"type":      "text",
				"mime_type": "application/json",
			},
		},
	}

	interBytes, err := json.Marshal(interPayload)
	if err != nil {
		return "", fmt.Errorf("error marshalling payload: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", interactionsURL, bytes.NewBuffer(interBytes))
	if err != nil {
		return "", fmt.Errorf("error creating request: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("x-goog-api-key", apiKey)

	resp, err := client.Do(httpReq)
	if err != nil {
		return "", fmt.Errorf("ไม่สามารถติดต่อ Google Gemini API ได้: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("error reading response: %w", err)
	}

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		var errData map[string]interface{}
		_ = json.Unmarshal(respBody, &errData)
		errMsg := fmt.Sprintf("Google API error (status %d)", resp.StatusCode)
		if e, ok := errData["error"].(map[string]interface{}); ok {
			if msg, ok := e["message"].(string); ok {
				errMsg = msg
			}
		}
		return "", fmt.Errorf("Google Gemini API: %s", errMsg)
	}

	return string(respBody), nil
}

// -------------------------------------------------------------
// PROVIDER 2: OpenAI API (ChatGPT)
// -------------------------------------------------------------
func callOpenAIChatAPI(ctx context.Context, apiKey, baseURL, model, prompt string) (string, error) {
	if baseURL == "" {
		baseURL = "https://api.openai.com/v1"
	}
	cleanBase := strings.TrimRight(baseURL, "/")
	apiURL := fmt.Sprintf("%s/chat/completions", cleanBase)

	client := &http.Client{
		Timeout: 75 * time.Second,
	}

	reqPayload := map[string]interface{}{
		"model": model,
		"messages": []map[string]interface{}{
			{
				"role":    "system",
				"content": "You are an expert exam creator for high school students. Respond strictly with valid JSON.",
			},
			{
				"role":    "user",
				"content": prompt,
			},
		},
		"response_format": map[string]interface{}{
			"type": "json_object",
		},
		"temperature": 0.2,
	}

	jsonBytes, err := json.Marshal(reqPayload)
	if err != nil {
		return "", fmt.Errorf("error marshalling OpenAI payload: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", apiURL, bytes.NewBuffer(jsonBytes))
	if err != nil {
		return "", fmt.Errorf("error creating OpenAI request: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("Authorization", fmt.Sprintf("Bearer %s", apiKey))

	resp, err := client.Do(httpReq)
	if err != nil {
		return "", fmt.Errorf("ไม่สามารถติดต่อ OpenAI API ได้: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("error reading OpenAI response: %w", err)
	}

	if resp.StatusCode != http.StatusOK {
		var errResp struct {
			Error struct {
				Message string `json:"message"`
				Type    string `json:"type"`
			} `json:"error"`
		}
		_ = json.Unmarshal(respBody, &errResp)
		errMsg := errResp.Error.Message
		if errMsg == "" {
			errMsg = fmt.Sprintf("HTTP Status %d", resp.StatusCode)
		}
		return "", fmt.Errorf("OpenAI API Error: %s", errMsg)
	}

	var chatResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}

	if err := json.Unmarshal(respBody, &chatResp); err != nil || len(chatResp.Choices) == 0 {
		return "", fmt.Errorf("invalid response format from OpenAI: %s", string(respBody))
	}

	return chatResp.Choices[0].Message.Content, nil
}

// -------------------------------------------------------------
// PROVIDER 3: Anthropic Claude API
// -------------------------------------------------------------
func callAnthropicMessagesAPI(ctx context.Context, apiKey, model, prompt string, mediaParts []MediaPart) (string, error) {
	apiURL := "https://api.anthropic.com/v1/messages"

	client := &http.Client{
		Timeout: 75 * time.Second,
	}

	var contentBlocks []map[string]interface{}

	// Add PDF document block if any
	for _, m := range mediaParts {
		if m.MimeType == "application/pdf" {
			contentBlocks = append(contentBlocks, map[string]interface{}{
				"type": "document",
				"source": map[string]interface{}{
					"type":       "base64",
					"media_type": "application/pdf",
					"data":       m.Base64Data,
				},
			})
		}
	}

	// Add text prompt block
	contentBlocks = append(contentBlocks, map[string]interface{}{
		"type": "text",
		"text": prompt,
	})

	reqPayload := map[string]interface{}{
		"model":      model,
		"max_tokens": 4096,
		"system":     "You are an expert exam creator for high school LMS. Always respond with pure valid JSON matching the requested structure. Never include introductory text.",
		"messages": []map[string]interface{}{
			{
				"role":    "user",
				"content": contentBlocks,
			},
		},
		"temperature": 0.2,
	}

	jsonBytes, err := json.Marshal(reqPayload)
	if err != nil {
		return "", fmt.Errorf("error marshalling Anthropic payload: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", apiURL, bytes.NewBuffer(jsonBytes))
	if err != nil {
		return "", fmt.Errorf("error creating Anthropic request: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("x-api-key", apiKey)
	httpReq.Header.Set("anthropic-version", "2023-06-01")

	resp, err := client.Do(httpReq)
	if err != nil {
		return "", fmt.Errorf("ไม่สามารถติดต่อ Anthropic Claude API ได้: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("error reading Anthropic response: %w", err)
	}

	if resp.StatusCode != http.StatusOK {
		var errResp struct {
			Error struct {
				Message string `json:"message"`
				Type    string `json:"type"`
			} `json:"error"`
		}
		_ = json.Unmarshal(respBody, &errResp)
		errMsg := errResp.Error.Message
		if errMsg == "" {
			errMsg = fmt.Sprintf("HTTP Status %d", resp.StatusCode)
		}
		return "", fmt.Errorf("Anthropic API Error: %s", errMsg)
	}

	var msgResp struct {
		Content []struct {
			Type string `json:"type"`
			Text string `json:"text"`
		} `json:"content"`
	}

	if err := json.Unmarshal(respBody, &msgResp); err != nil || len(msgResp.Content) == 0 {
		return "", fmt.Errorf("invalid response format from Anthropic: %s", string(respBody))
	}

	var sb strings.Builder
	for _, c := range msgResp.Content {
		if c.Type == "text" {
			sb.WriteString(c.Text)
		}
	}

	return sb.String(), nil
}

// -------------------------------------------------------------
// PROVIDER 4: OpenAI-Compatible Custom Provider (DeepSeek, Groq, Ollama)
// -------------------------------------------------------------
func callOpenAICompatibleAPI(ctx context.Context, apiKey, baseURL, model, prompt string) (string, error) {
	if baseURL == "" {
		baseURL = "https://api.deepseek.com/v1"
	}
	cleanBase := strings.TrimRight(baseURL, "/")
	apiURL := cleanBase
	if !strings.HasSuffix(apiURL, "/chat/completions") {
		apiURL = fmt.Sprintf("%s/chat/completions", cleanBase)
	}

	client := &http.Client{
		Timeout: 75 * time.Second,
	}

	reqPayload := map[string]interface{}{
		"model": model,
		"messages": []map[string]interface{}{
			{
				"role":    "system",
				"content": "You are an expert exam creator for high school students. Respond strictly with valid JSON without markdown wrapping if possible.",
			},
			{
				"role":    "user",
				"content": prompt,
			},
		},
		"temperature": 0.2,
	}

	jsonBytes, err := json.Marshal(reqPayload)
	if err != nil {
		return "", fmt.Errorf("error marshalling payload: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", apiURL, bytes.NewBuffer(jsonBytes))
	if err != nil {
		return "", fmt.Errorf("error creating request: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	if apiKey != "" {
		httpReq.Header.Set("Authorization", fmt.Sprintf("Bearer %s", apiKey))
	}

	resp, err := client.Do(httpReq)
	if err != nil {
		return "", fmt.Errorf("ไม่สามารถติดต่อ Custom API Server (%s) ได้: %w", baseURL, err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("error reading response: %w", err)
	}

	if resp.StatusCode != http.StatusOK {
		var errResp struct {
			Error struct {
				Message string `json:"message"`
			} `json:"error"`
			Message string `json:"message"`
		}
		_ = json.Unmarshal(respBody, &errResp)
		errMsg := errResp.Error.Message
		if errMsg == "" {
			errMsg = errResp.Message
		}
		if errMsg == "" {
			errMsg = fmt.Sprintf("HTTP Status %d (%s)", resp.StatusCode, string(respBody))
		}
		return "", fmt.Errorf("Custom Provider API Error: %s", errMsg)
	}

	var chatResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}

	if err := json.Unmarshal(respBody, &chatResp); err != nil || len(chatResp.Choices) == 0 {
		return "", fmt.Errorf("invalid response format from Custom Provider: %s", string(respBody))
	}

	return chatResp.Choices[0].Message.Content, nil
}

func extractJSONBlock(raw string) string {
	raw = strings.TrimSpace(raw)
	if strings.HasPrefix(raw, "```json") {
		raw = strings.TrimPrefix(raw, "```json")
		if idx := strings.LastIndex(raw, "```"); idx != -1 {
			raw = raw[:idx]
		}
	} else if strings.HasPrefix(raw, "```") {
		raw = strings.TrimPrefix(raw, "```")
		if idx := strings.LastIndex(raw, "```"); idx != -1 {
			raw = raw[:idx]
		}
	}
	return strings.TrimSpace(raw)
}

func normalizeAIQuestion(q AIQuizQuestionItem) *AIQuizQuestionItem {
	qText := strings.TrimSpace(q.QuestionText)
	if qText == "" {
		return nil
	}

	qType := strings.ToUpper(strings.TrimSpace(q.QuestionType))
	if qType == "TRUE_FALSE" || qType == "TF" {
		qType = "TRUE_FALSE"
		options := []string{"จริง", "เท็จ"}
		corr := strings.TrimSpace(q.CorrectAnswer)
		corrLower := strings.ToLower(corr)

		if corrLower == "true" || corrLower == "t" || corr == "จริง" || corr == "ถูก" || corr == "1" || corr == "ก" {
			corr = "จริง"
		} else {
			corr = "เท็จ"
		}

		pts := q.Points
		if pts <= 0 {
			pts = 1
		}

		return &AIQuizQuestionItem{
			QuestionText:  qText,
			QuestionType:  "TRUE_FALSE",
			Options:       options,
			CorrectAnswer: corr,
			Points:        pts,
			Explanation:   strings.TrimSpace(q.Explanation),
		}
	}

	// MULTIPLE_CHOICE
	cleanedOptions := make([]string, 0, len(q.Options))
	for _, opt := range q.Options {
		trimmed := strings.TrimSpace(opt)
		if trimmed != "" {
			cleanedOptions = append(cleanedOptions, trimmed)
		}
	}

	if len(cleanedOptions) < 2 {
		return nil
	}

	corr := strings.TrimSpace(q.CorrectAnswer)
	matched := false
	for _, opt := range cleanedOptions {
		if strings.EqualFold(opt, corr) {
			corr = opt
			matched = true
			break
		}
	}

	if !matched {
		corrLower := strings.ToLower(corr)
		idx := -1
		switch corrLower {
		case "a", "1", "ก":
			idx = 0
		case "b", "2", "ข":
			idx = 1
		case "c", "3", "ค":
			idx = 2
		case "d", "4", "ง":
			idx = 3
		}
		if idx >= 0 && idx < len(cleanedOptions) {
			corr = cleanedOptions[idx]
			matched = true
		}
	}

	if !matched {
		corr = cleanedOptions[0]
	}

	pts := q.Points
	if pts <= 0 {
		pts = 1
	}

	return &AIQuizQuestionItem{
		QuestionText:  qText,
		QuestionType:  "MULTIPLE_CHOICE",
		Options:       cleanedOptions,
		CorrectAnswer: corr,
		Points:        pts,
		Explanation:   strings.TrimSpace(q.Explanation),
	}
}
